version: '3'

services:
  backend:
    build: login-backend/
    depends_on:
      - 'database'
    volumes:
      - './login-backend:/src/app'
      - '/src/app/node_modules'
    environment:
    - filePath="http://host.docker.internal:3002/"
    - PORT = 3002
    ports: 
      - '3002:3002'

  app:
    build: login-app/
    depends_on:
      - 'database'
      - 'backend'
    volumes:
      - './login-app:/web'
      - '/web/node_modules'
    environment:
    - filePath="http://host.docker.internal:3003/"
    - PORT=3003    
    ports:
    - '3003:3003'
    stdin_open: true

  database:
    build: postgresql/
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: password
      
